name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: git mingw-w64-i686-gcc libtool mingw-w64-i686-autotools mingw-w64-i686-libpng mingw-w64-i686-ffmpeg
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./build.sh
          make test
          ./create_release.sh
      - name: Write Release.txt
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            Release.txt
            yummy-latest.zip
          asset_name: yummy-windows-x86
          tag: ${{ github.ref }}
          overwrite: true

